jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Install gpg secret key
      run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish package
      run: mvn --batch-mode deploy -DskipTests=true -DreleaseBuild=true -Dgpg.passphrase=${{
        secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out the repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build SQLancer
      run: mvn -B package -DskipTests=true
    - continue-on-error: true
      name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        push: false
        repository: mrigger/sqlancer
        tag_with_ref: true
        username: ${{ secrets.DOCKER_USERNAME }}
name: Publish package to the Maven Central Repository and Docker Hub
on:
  repository_dispatch:
    types: trigger-ga___release.yml
